engines:
  phpcodesniffer:
    enabled: true
    checks:
      Squiz Scope MethodScope Missing:
        enabled: false
      PSR1 Methods CamelCapsMethodName NotCamelCaps:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - php

ratings:
  paths:
    - src/**
    - "**.php"

exclude_paths:
  - tests/**/*
