language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --testdox --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
